// load shared libraries
@Library('jenkins_ss_shared') _

pipeline
{
	agent {label 'LX-MASTER'}
	parameters 
	{
		// get Core branch
		string(defaultValue: 'branches/devmt/CORE_ID_STP_2019', description: 'Enter Relative CORE SVN Path to branch root (Note: https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/Core/ will be added automatically)', name: 'CORE_SVN_Branch')
		// get ID branch
		string(defaultValue: 'trunk', description: 'Enter Relative UOBI SVN Path to branch root (Note: https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/ID/ will be added automatically)', name: 'UOBI_SVN_Branch')
	}
	environment 
	{
		// generate build 
		def build_version = sh ( script: 'date +%d%m%Y_%H%M%S',	returnStdout: true ).trim()
	}

	stages
	{
		
		stage("Initialize Jenkins Environment")	
		{
			steps
			{
				sh "if [ -d ${WORKSPACE}/logs ]; then rm -rf ${WORKSPACE}/logs/*; else mkdir -p ${WORKSPACE}/logs; fi"
				sh "echo '------------------------------------------------' > ${WORKSPACE}/logs/pipeline.log"
				sh "echo 'Jenkins pipeline started at : '\$(date) >> ${WORKSPACE}/logs/pipeline.log"
				sh "echo '------------------------------------------------' >> ${WORKSPACE}/logs/pipeline.log"
			
			}
		}
		
		stage("Checkout CORE Code From SVN") 
		{
			steps
			{
				echo "CORE - Checking out https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/Core/${CORE_SVN_Branch}"
				sh "echo 'CORE - Checking out https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/Core/'${CORE_SVN_Branch} >> ${WORKSPACE}/logs/pipeline.log"
				checkout([
					$class: 'SubversionSCM', 
					additionalCredentials: [], 
					excludedCommitMessages: '', 
					excludedRegions: '', 
					excludedRevprop: '', 
					excludedUsers: '', 
					filterChangelog: false, 
					ignoreDirPropChanges: false, 
					includedRegions: '', 
					locations: [[credentialsId: 'JENKINS_SVN', 
								depthOption: 'infinity', 
								ignoreExternalsOption: true, 
								local: "./svn_src/CORE", 
								remote: "https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/Core/${CORE_SVN_Branch}" ]], 
					workspaceUpdater: [$class: 'CheckoutUpdater']
				])

			}
		}

		stage("CORE - Prepare Sources")
		{		
			steps
			{
				script
				{
					def corePOMVersion = getPOMVersion("${WORKSPACE}/svn_src/CORE/pom.xml")
					//def corePOMVersion = getCorePOMVersion("/tmp/pom.xml")
					echo "POM Version - ${corePOMVersion}"
					echo "Build Version - ${env.build_version}"
					sh "echo Tag:  ${corePOMVersion}_${env.build_version} '---------' >> ${WORKSPACE}/logs/pipeline.log"
				}
			}
		}

		stage("Checkout ID Code From SVN") 
		{
			steps
			{
				echo "CORE - Checking out https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/ID/${UOBI_SVN_Branch}"
				sh "echo 'CORE - Checking out https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/ID/'${UOBI_SVN_Branch} >> ${WORKSPACE}/logs/pipeline.log"
				checkout([
					$class: 'SubversionSCM', 
					additionalCredentials: [], 
					excludedCommitMessages: '', 
					excludedRegions: '', 
					excludedRevprop: '', 
					excludedUsers: '', 
					filterChangelog: false, 
					ignoreDirPropChanges: false, 
					includedRegions: '', 
					locations: [[credentialsId: 'JENKINS_SVN', 
								depthOption: 'infinity', 
								ignoreExternalsOption: true, 
								local: "./svn_src/ID", 
								remote: "https://lxclstsgv99.sg.uobnet.com:9999/svn/PLCE_SS/ID/${UOBI_SVN_Branch}" ]], 
					workspaceUpdater: [$class: 'CheckoutUpdater']
				])

			}
		}

		stage("ID - Prepare Sources")
		{		
			steps
			{
				script
				{
					def IDPOMVersion = getPOMVersion("${WORKSPACE}/svn_src/ID/pom.xml")
					//def corePOMVersion = getCorePOMVersion("/tmp/pom.xml")
					echo "POM Version - ${IDPOMVersion}"
					echo "Build Version - ${env.build_version}"
					sh "echo Tag:  ${IDPOMVersion}_${env.build_version} '---------' >> ${WORKSPACE}/logs/pipeline.log"
				}
			}
		}

/*
		stage("CORE - Upload Source Package")
		{
			steps
			{
				wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: "${Password}", var: 'Password']]]) 
				{
					sh "${WORKSPACE}/pipeline/shell/pipeline.sh SIGNON ald_user=${Username} ald_scrt=${Password} country=CORE module=ONLINE run_mode=${Run_Mode} queue_timeout=${Queue_Timeout} >> ${WORKSPACE}/logs/pipeline.log"
				}
			}
		}

		stage("CORE - Set Development Env")
		{
			steps
			{
				echo "CORE - ONLINE - Set Development Env"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh SETDEVENV country=CORE module=ONLINE >> ${WORKSPACE}/logs/pipeline.log"
			}
		}  

		stage("CORE - Get Latest From Aldon")
		{
			steps
			{
				echo "CORE - Get Latest From Aldon"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh GETLATEST country=CORE module=ONLINE >> ${WORKSPACE}/logs/pipeline.log"
			}
		}

		stage("CORE - Generate Diff Reports")
		{
			steps
			{
				echo "CORE - Generate Diff Reports"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh GENDIFF country=CORE module=ONLINE >> ${WORKSPACE}/logs/pipeline.log"
			}
			post
			{
				success
				{
					archiveArtifacts(artifacts: "ald_devenv_root/CORE/ONLINE/CORE_*files.txt", allowEmptyArchive: true)
				}
			}
		}

		stage("CORE - Checkout Changed Objects")
		{
			when
			{
				expression { return ! params.Only_Generate_Reports }
			}
			steps
			{
				echo "CORE - Checkout Changed Objects From Aldon"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh CHECKOUT country=CORE module=ONLINE ald_task=${CORE_Aldon_Task} >> ${WORKSPACE}/logs/pipeline.log"
			}
		}

		stage("CORE - Update Dev Environment")
		{
			when
			{
				expression { return ! params.Only_Generate_Reports }
			}
			steps
			{
				echo "CORE - Update Dev Environment"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh UPDATEDEVENV country=CORE module=ONLINE >> ${WORKSPACE}/logs/pipeline.log"
			}
		}

		stage("CORE - Add New Objects to Aldon")
		{
			when
			{
				expression { return ! params.Only_Generate_Reports }
			}
			steps
			{
				echo "CORE - Add New Objects to Aldon"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh ADDNEWOBJECTS country=CORE module=ONLINE ald_task=${CORE_Aldon_Task} >> ${WORKSPACE}/logs/pipeline.log"
			}
		}

		stage("CORE - Mark As Delete from Aldon")
		{
			when 
			{
				allOf
				{
					expression { params.CORE_Auto_Delete == 'NO' || params.CORE_Auto_Delete == 'YES' }
					expression { return ! params.Only_Generate_Reports }
				}
			}
			environment 
			{
				def delobjectsurl = "${env.BUILD_URL}/artifact/ald_devenv_root/CORE/ONLINE/CORE_ONLINE_deleted_files.txt"
				def delconfirmation = "YES"
			}
			steps
			{
				script
				{
					if (params.CORE_Auto_Delete == 'NO')
					{
						input ( id: 'delconfirmation', message: 'CORE - Proceed with mark as delete [YES/NO]?', parameters: [choice(choices: 'NO\nYES', description: "Deleted objects:\n${delobjectsurl}", name: 'CORE_MARK_AS_DELETE')])
					}
					
					if (delconfirmation == 'YES')
					{
						echo "CORE - Marking Objects as Deleted in Aldon"
						sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
						sh "${WORKSPACE}/pipeline/shell/pipeline.sh MARKASDELETE country=CORE module=ONLINE ald_task=${CORE_Aldon_Task} >> ${WORKSPACE}/logs/pipeline.log"
					}
					else
					{
						echo "CORE - Skipping Mark As Delete as NO Selected"
						sh "echo \$(date)'- INFO [CORE] [ald_mark_for_delete]: Skipping Mark As Delete as NO Selected...' >> ${WORKSPACE}/logs/pipeline.log"
					}
				}
			}
		}

		stage("CORE - Check-in Objects to Aldon")
		{                                  
			when
			{
				expression { return ! params.Only_Generate_Reports }
			}
			steps
			{
				echo "CORE - Check-in Objects to Aldon"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh CHECKIN country=CORE module=ONLINE >> ${WORKSPACE}/logs/pipeline.log"
			}
		}
		
		stage("CORE - Aldon Sign Off and Shutdown")
		{                                   
			steps
			{
				echo "CORE - Sign Off and Shutdown From Aldon"
				sh "chmod 755 ${WORKSPACE}/pipeline/shell/pipeline.sh"
				sh "${WORKSPACE}/pipeline/shell/pipeline.sh SHUTDOWN >> ${WORKSPACE}/logs/pipeline.log"
			}
		}
		*/
	}
	
	post
	{
		always 
		{
			archiveArtifacts(artifacts: "logs/pipeline.log", allowEmptyArchive: true)
		}
	}
}

